### ISSUE TITLE
link of simple recon weight not available

### ISSUE THREAD

**Issue by yotofu** [nianticlabs/doubletake#2]
![image](https://github.com/user-attachments/assets/1b93745b-e804-4910-b9b6-d32ad4e7321f)
![image](https://github.com/user-attachments/assets/95145bf1-ffd3-4da0-ad59-869a9b7fd371)
As the title, link of simple recon weight  is not available

**Comment by mohammed-amr** [comment]
Thanks for the heads up! Fixed now and should work. 🙏
